apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
