apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-mgmt.componentName" (dict "ctx" $ "component" "backend") }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.jwtSecret | quote }}
