apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-mgmt.componentName" (dict "ctx" $ "component" "backend") }}
  labels:
    {{- include "user-mgmt.labels" (dict "ctx" $ "component" "backend") | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.jwtSecret | quote }}
