apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-mgmt.componentName" (dict "ctx" $ "component" "frontend") }}
  labels:
    {{- include "user-mgmt.labels" (dict "ctx" $ "component" "frontend") | nindent 4 }}
data:
  PORT: {{ .Values.frontend.service.port | quote }}
  NODE_ENV: {{ .Values.frontend.service.nodeEnv | quote }}

