apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-mgmt.componentName" (dict "ctx" $ "component" "frontend") }}
  labels:
    {{- include "user-mgmt.labels" (dict "ctx" $ "component" "frontend") | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    {{- toYaml .Values.frontend.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "user-mgmt.selectorLabels" (dict "ctx" $ "component" "frontend") | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/frontend/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "user-mgmt.selectorLabels" (dict "ctx" $ "component" "frontend") | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.frontend.image.name }}
          image: {{ include "user-mgmt.image" .Values.frontend.image | quote }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "user-mgmt.componentName" (dict "ctx" $ "component" "frontend") }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.probes.readiness | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.frontend.probes.liveness | nindent 12 }}
